package cc.sukazyo.cono.morny.core.internal;


import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

/**
 * The annotation indicates that the field is generated by the sbt plugin {@code sbtBuildInfo}.
 * @since 1.0.0-alpha4
 */
@Documented
@Target({ElementType.FIELD, ElementType.METHOD})
public @interface BuildConfigField {}
