// $COVERAGE-OFF$
package cc.sukazyo.cono.morny

/** This object was generated by sbt-buildinfo. */
case object BuildConfig {
	/** The value is "Morny Coeur". */
	val name: String = "Morny Coeur"
	/** The value is "2.0.0-alpha21-SNAPSHOT". */
	val version: String = "2.0.0-alpha21-SNAPSHOT"
	/** The value is "3.4.1". */
	val scalaVersion: String = "3.4.1"
	/** The value is "1.10.0". */
	val sbtVersion: String = "1.10.0"
	/** The value is "2.0.0-alpha21-SNAPSHOT". */
	val VERSION: String = "2.0.0-alpha21-SNAPSHOT"
	/** The value is "2.0.0-alpha21-SNAPSHOT+gitbd958708.δ". */
	val VERSION_FULL: String = "2.0.0-alpha21-SNAPSHOT+gitbd958708.δ"
	/** The value is "2.0.0-alpha21". */
	val VERSION_BASE: String = "2.0.0-alpha21"
	/** The value is scala.None. */
	val VERSION_DELTA: scala.Option[String] = scala.None
	/** The value is "xinzheng". */
	val CODENAME: String = "xinzheng"
	/** The value is 1739975193572L. */
	val CODE_TIMESTAMP: scala.Long = 1739975193572L
	/** The value is "bd95870864075e9921257e14bf446f53d4bc5e02". */
	val COMMIT: String = "bd95870864075e9921257e14bf446f53d4bc5e02"
	/** The value is false. */
	val CLEAN_BUILD: scala.Boolean = false
	/** The value is "https://github.com/Eyre-S/Coeur-Morny-Cono". */
	val CODE_STORE: String = "https://github.com/Eyre-S/Coeur-Morny-Cono"
	/** The value is "https://github.com/Eyre-S/Coeur-Morny-Cono/commit/%s". */
	val COMMIT_PATH: String = "https://github.com/Eyre-S/Coeur-Morny-Cono/commit/%s"
	override val toString: String = {
		"name: %s, version: %s, scalaVersion: %s, sbtVersion: %s, VERSION: %s, VERSION_FULL: %s, VERSION_BASE: %s, VERSION_DELTA: %s, CODENAME: %s, CODE_TIMESTAMP: %s, COMMIT: %s, CLEAN_BUILD: %s, CODE_STORE: %s, COMMIT_PATH: %s".format(
			name, version, scalaVersion, sbtVersion, VERSION, VERSION_FULL, VERSION_BASE, VERSION_DELTA, CODENAME, CODE_TIMESTAMP, COMMIT, CLEAN_BUILD, CODE_STORE, COMMIT_PATH
		)
	}
}
// $COVERAGE-ON$
