name: assembly jar - Build
on: [workflow_call]
jobs:
  assembly:
    name: "generate assembly jar"
    runs-on: ubuntu-latest
    steps:
      - name: "setup project - with built"
        uses: actions/cache/restore@v4
        with:
          path: "./"
          key: ${{ runner.os }}-coeur-build-${{ github.sha }}
          fail-on-cache-miss: 'true'
      - name: "setup java"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: sbt
      - name: "setup sbt"
        uses: sbt/setup-sbt@v1
      - name: "SBT: build assembly jar"
        run: sbt assembly
      - name: "upload assembly jar"
        uses: actions/upload-artifact@v7
        with:
          archive: 'false'
          name: 'assembly jars'
          path: ./morny-coeur/target/*-assembly-*.jar
