name: assembly jar - Check
on: [workflow_call]
jobs:
  run-assembly:
    name: "run"
    runs-on: ubuntu-latest
    steps:
      - name: "setup assembly jar"
        uses: actions/download-artifact@v8
        with:
          pattern: 'Morny Coeur-assembly-*.jar'
          path: ./assembles/
      - name: "setup java"
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "run assembly jar"
        id: assembly-run
        shell: bash
        run: |
          
          exec 5>&1
          outputs=$(java -jar ./assembles/*.jar -q -v | tee >(cat - >&5))
          
          echo '# Assembly Jar Runs' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo 'The execution result while running assembly jar:' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "$outputs" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
